version: '3'
services:

  db:
    image: mysql:latest
    container_name: bd_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - my_network
    volumes: 
      - bd:/database
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  api:
    container_name: fastapi
    depends_on:
      - db
    build:
      context: ./api
    ports:
      - "8000:8000"
    networks:
      - my_network
    volumes: 
      - reports:/app/reports

  backend:
    container_name: backend
    depends_on:
      - db
    build:
      context: ./backend 
    networks:
      - my_network
    volumes: 
      - reports:/app/reports

networks:
  my_network:
    driver: bridge
  
volumes: 
  reports:
  bd: