version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: mydb
    environment:
      MYSQL_DATABASE: Challenge
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - './sql/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - bd:/database
    networks:
      - my_network

  api:
    container_name: fastapi
    depends_on:
      - db
    build:
      context: ./api
    ports:
      - "8000:8000"
    networks:
      - my_network
    volumes: 
      - reports:/app/reports

  backend:
    container_name: backend
    restart: always
    depends_on:
      - db
    build:
      context: ./backend 
    networks:
      - my_network
    volumes: 
      - reports:/app/reports
  
  bd_init:
    container_name: initbd
    depends_on:
      - db
    build:
      context: ./BD 
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
  
volumes: 
  reports:
  bd: